# NUMPY PRACTICE

Practice source: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

### 1. **Import numpy** as np and see the version

In [6]:
import numpy as np
print(np.__version__)

1.16.5


### 2. How to **create a 1D array**?

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to **create a boolean array**?

In [44]:
np.full((3,3), 1, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to **extract items** that satisfy a **given condition** from 1D array?

In [50]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [16]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### 5. How to **replace** items that satisfy a condition with another value in numpy array?

In [19]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to **replace** items that satisfy a condition without affecting the original array?

In [14]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr) 
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, 'hello', arr).tolist()
print(arr) 
out

[0 1 2 3 4 5 6 7 8 9]


['0', 'hello', '2', 'hello', '4', 'hello', '6', 'hello', '8', 'hello']

### 7. How to **reshape** an array?

In [10]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to **stack two arrays vertically**?

In [14]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.concatenate([a,b], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to **stack** two arrays **horizontally**?

In [39]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [43]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [44]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How **to generate custom sequences** in numpy without hardcoding?

In [54]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), (np.tile(a,3))]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How **to get the common items** between two python numpy arrays?

In [58]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 12. How to **remove** from one array those items that exist in another?

In [60]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# menghapus elemen a yang ada di b
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions **where elements of two arrays match**?

In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b) # mencari element yang ke-berapa....?

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to **extract all numbers** between a given **range** from a numpy array?

In [71]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [76]:
a = np.arange(15)

#cara pertama
index = np.where((a>=5) & (a <= 10) )
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
# cara kedua
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
# cara ketiga
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. How to **make a python function** that handles scalars to work on numpy arrays?

In [5]:
import numpy as np
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b) # menyeleksi elemen yang terbesar

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to **swap two columns** in a 2d numpy array?

In [20]:
import numpy as np
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to **swap two rows** in a 2d numpy array?

In [23]:
arr = np.arange(9).reshape(3,3)
arr
arr[[2, 1, 0], :] #memanipulasi urutan baris

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 18. How to **reverse the rows** of a 2D array?

In [24]:
arr = np.arange(9).reshape(3,3)
arr[::-1] #membalikkan urutan baris, yang pertama menjadi terakhir

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to **reverse the columns** of a 2D array?

In [31]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1] #membalikkan urutan kolom

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to **create a 2D array** containing random floats between 5 and 10?

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [42]:
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[5.2319574 , 7.77452588, 9.5796431 ],
       [8.57229214, 8.62337148, 6.47575659],
       [8.06380043, 6.57893043, 7.66786073],
       [8.99184526, 8.18986595, 8.32707241],
       [5.17657948, 7.92689308, 8.75881498]])